---
  - name: Instala o pacotes necessarios
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - docker-ce docker-ce-cli containerd.io
      state: present
    become: true
    become_method: sudo
    become_user: root

  #- name: Copia o script de compilacao libreswan
  #  template:
  #    src: compila_libreswan.sh.j2
  #    dest: /usr/src/compila_libreswan.sh
  #    owner: root
  #    group: root
  #    mode: 0755
  #  become: true
  #  become_method: sudo
  #  become_user: root

  #- name: Copia o pacote de instalacao libreswan
  #  copy:
  #    src: libreswan-3.27.tar.gz
  #    dest: /usr/src/
  #    force: no
  #  become: true
  #  become_method: sudo
  #  become_user: root


  #- name: Compila o libreswan
  #  shell: /usr/src/compila_libreswan.sh >> log.txt
  #  become: true
  #  become_method: sudo
  #  become_user: root
