---
  - name: Instala o pacotes necessarios
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - nginx
      state: present
    become: true
    become_method: sudo
    become_user: root

  - name: Adiciona usuario vagrant ao grupo docker
    user:
       name: vagrant
       shell: /bin/bash
       groups: docker
       append: yes
