# Configuraçoes do NGINX
- template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  become: true
  become_method: sudo
  become_user: root

#Configuracoes NGINX para proxy reverso
- template:
    src: proxy.conf.j2
    dest: /etc/nginx/proxy.conf
    owner: root
    group: root
    mode: 0644
  become: true
  become_method: sudo
  become_user: root

#Copia certificado auto-assinado
- template:
    src: localhost.crt.j2
    dest: /etc/ssl/certs/localhost.crt
    owner: root
    group: root
    mode: 0644
  become: true
  become_method: sudo
  become_user: root

#Copia chave
- template:
    src: localhost.key.j2
    dest: /etc/ssl/private/localhost.key
    owner: root
    group: root
    mode: 0644
  become: true
  become_method: sudo
  become_user: root

# Habilita o serviço do nginx automaico
- name: Habilitando o servico de NGINX
  systemd:
    state: restarted
    name: nginx
    enabled: yes
  become: true
  become_method: sudo
  become_user: root
