
# Habilita o serviço de regras de firewall
#- name: Desabilita servico Firewalld
#  systemd:
#    name: firewalld
#    state: stopped
#    enabled: no
#    daemon_reload: yes

# Cria Diretório que será armazenado as regras de firewall
- file:
    path: /etc/regras
    state: directory
    mode: 0755
  become: true
  become_method: sudo
  become_user: root

# Copia regras de firewall para diretorio conrrespondente
- template:
    src: firewall.sh.j2
    dest: /etc/regras/firewall.sh
    owner: root
    group: root
    mode: 0755
  become: true
  become_method: sudo
  become_user: root

# Copia regras de firewall para diretorio conrrespondente
- template:
    src: regras.service.j2
    dest: /etc/systemd/system/regras.service
    owner: root
    group: root
    mode: 0755
  become: true
  become_method: sudo
  become_user: root

# Habilita o serviço de regras de firewall
- name: Habilita o serviço de regras de firewall
  systemd:
    state: restarted
    name: regras
    enabled: yes
    daemon_reload: yes
  become: true
  become_method: sudo
  become_user: root
