- name: Starta container da aplicação
  docker_container:
    name: devops-challenge
    image: willienf/devops-challenge:latest
    state: started
    restart_policy: unless-stopped
    ports:
    - "8080:8080"
